language: node_js
node_js:
    - "11.12.0"

sudo: false


notifications:
  # 钉钉机器人消息推送部署结果
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=3ea2cb84a09ef03881b3842a600fe9f9aadabf9b439fc5490533de52569860db
  # 邮件发送部署结果通知
  email:
    recipients:
      - 951123033@qq.com
    on_success: change
    on_failure: always

# S: Build Lifecycle
before_install:
  - git config user.name "newhcw"
  - git config user.email "951123033@qq.com"
  - sed -i'' "s~https://github.com/huangchunwu/huangchunwu.github.io.git~https://${GH_TOKEN}@github.com/huangchunwu/huangchunwu.github.io.git~" _config.yml


install:
  - npm install hexo-cli -g
  - npm install
#  - gem install travis
#  - travis login --pro --github-token ${GH_TOKEN}

before_script:
  - export TZ='Asia/Shanghai'
  - chmod +x _travis.sh

script:
  - npm run deploy

after_success:
 # - LAST_BUILD_NUMBER=68
 # - for i in $(seq 1 $LAST_BUILD_NUMBER ); do  travis logs $i --delete --force ; done

after_script:
  # - ./_travis.sh

branches:
  only:
    - save #需要监听部署的分支
env:
  global:
   - GH_REF: github.com/huangchunwu/huangchunwu.github.io.git #更改为自己git地址
